//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gameee.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gameee.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A G1,15;V-14;H6;V14;G1,8;H6
        ///B G1,8;H6;V7;H-6;V-14;H4;V7
        ///C G7,3;V-2;H-6;V14;H6;V-2
        ///D G1,1;H4;V2;H2;V10;H-2;V2;H-4;V-14
        ///E G7,1;H-6;V14;H6;G1,8;H3
        ///F G7,1;H-6;V14;G1,8;H3
        ///G G7,3;V-2;H-6;V14;H6;V-7;H-2
        ///H G1,1;V14;G7,1;V14;G1,8;H6
        ///I G3,1;H2;G3,15;H2;G4,1;V14
        ///J G3,1;H2;G4,1;V14;H-4;V-2
        ///K G1,1;V14;G1,8;H6;V7;G5,1;V7
        ///L G1,1;V14;H6
        ///M G1,1;V14;G1,3;H6;G7,1;V14
        ///N G1,15;V-14;H3;V14;H3;V-14
        ///O G1,1;H6;V14;H-6;V-14
        ///P G1,15;V-14;H6;V7;H-6
        ///Q G5,15;H-4;V-14;H6;V14;H-2;V-3
        ///R G1,15;V-14;H6;V7;H-6;G5,8;V7
        ///S G7, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chars {
            get {
                return ResourceManager.GetString("chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b()Controls:\n()
        ///W  = Up
        ///A  = Left
        ///S  = Down
        ///D  = Right
        ///
        ///P  = Pause
        ///M  = Toggle music
        ///F  = Show FPS [hold]
        ///R  = Start game
        ///F1 = Show / Hide help
        ///
        ///
        ///\b()Music:\n()
        ///TeknoAXE - Terminal Velocity Johnson \color(64,160,255)\ltmark()[link]\rbmark()\color(255,255,255).
        /// </summary>
        internal static string controls {
            get {
                return ResourceManager.GetString("controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ThresholdOfInsanity {
            get {
                return ResourceManager.GetStream("ThresholdOfInsanity", resourceCulture);
            }
        }
    }
}
